# Generated by Django 4.1.5 on 2023-01-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0003_nombre_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celulares',
            name='',
        ),
    ]
